"""
You are given two strings s and t.
String t is generated by random shuffling string s 
    and then add one more letter at a random position.
Return the letter that was added to t.
"""
from collections import Counter 


def difference(s, t):



    # a = set(s) 
    # b = set(t) 

    a = Counter(s)
    b = Counter(t)

    if a-b != Counter(): 
        return a-b 
    else: 
        return b-a 

s = "abcd"
t = "abcde" 

print( list(difference(s, t))[0] )